# Generated by Django 4.2.3 on 2023-07-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_party_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
